---
title: "case_studies"
created_by: Balasubramanian P
output: html_document
---


```{r, loading library Packages, echo=TRUE}
library(readr)
library(dplyr)
library(ggplot2)
library(dplyr)
library(tidyr)
library(data.table)
library(arrow)
```

```{r}
source('/cloud/project/R/pivot_fn.R')
```



```{r, Readingcsv file, echo=TRUE }

folder_path <- '/cloud/project/'
frddata <- read_csv_arrow(paste0(folder_path,'Train-1542865627584.csv'))
```

```{r, IP data, echo=TRUE}
Ipdata <- read_csv_arrow(paste0(folder_path,'Train_Inpatientdata-1542865627584.csv'))

Ipdata_1 <- Ipdata %>% mutate(ndays_claims = (ClaimEndDt - ClaimStartDt),
                         ndays_admis = (DischargeDt - AdmissionDt)
                          ) %>%
  dplyr::group_by(Provider) %>% 
  summarise(
    IP_Nclaims = n_distinct(ClaimID),
    IP_NBeneids = n_distinct(BeneID),
    IP_aveclaimdays = mean(ndays_claims),
    IP_aveadmtdays =  mean(ndays_admis), 
    IP_amtReim_pclm = mean(InscClaimAmtReimbursed),
    IP_dedtamtpaid = mean(DeductibleAmtPaid),
    IP_avepys_count = (n_distinct(AttendingPhysician) / n_distinct(ClaimID) ),
    IP_aveoprpys_count = (n_distinct(OperatingPhysician) / n_distinct(ClaimID) ),
    IP_aveothpys_count = (n_distinct(OtherPhysician) / n_distinct(ClaimID) )
  ) %>% select(Provider,IP_Nclaims,IP_NBeneids,IP_aveclaimdays,IP_aveadmtdays,IP_amtReim_pclm,IP_dedtamtpaid,
               IP_avepys_count,IP_aveothpys_count,IP_aveothpys_count)
```


```{r, OP data, echo=TRUE}
Opdata <- read_csv_arrow(paste0(folder_path,'Train_Outpatientdata-1542865627584.csv'))

Opdata_1 <- Opdata %>% mutate(ndays_claims = (ClaimEndDt - ClaimStartDt)
                          ) %>%
  dplyr::group_by(Provider) %>% 
  summarise(
    OP_Nclaims = n_distinct(ClaimID),
    OP_NBeneids = n_distinct(BeneID),
    OP_aveclaimdays = mean(ndays_claims),
    OP_amtReim_pclm = mean(InscClaimAmtReimbursed), 
    OP_dectamtpd_pclm = mean(DeductibleAmtPaid),
    OP_avepys_count = (n_distinct(AttendingPhysician) / n_distinct(ClaimID) ),
    OP_aveoprpys_count = (n_distinct(OperatingPhysician) / n_distinct(ClaimID) ),
    OP_aveothpys_count = (n_distinct(OtherPhysician) / n_distinct(ClaimID) )
  ) %>% select(Provider,OP_Nclaims,OP_NBeneids,OP_aveclaimdays,OP_amtReim_pclm,
               OP_dectamtpd_pclm,OP_avepys_count,OP_aveothpys_count,OP_aveothpys_count)

```


```{r}


Bnfydata <- read_csv_arrow(paste0(folder_path,'Train_Beneficiarydata-1542865627584.csv'))

Bnfydata_1 <- Bnfydata %>% 
  mutate(
    Bene_alive = if_else(is.na(DOD) ,1,0)
  ) 


racedata <- bind_cols(Bnfydata_1, model.matrix(~ Race - 1, data = Bnfydata_1))


```



```{r, Merge all data , echo=TRUE}

IP_diag <- data_convert_fn(Ipdata, "ClmDiagnosisCode_" )
IP_proc <- data_convert_fn(Ipdata, "ClmProcedureCode_" )
IP_diagroup <- data_convert_fn(Ipdata, "DiagnosisGroupCode" )

OP_diag <- data_convert_fn(Opdata, "ClmDiagnosisCode_" )
OP_proc <- data_convert_fn(Opdata, "ClmProcedureCode_" )
OP_diagroup <- data_convert_fn(Opdata, "DiagnosisGroupCode" )


```

